#!/bin/bash

WorkDir=/Volumes/TOSHIBA/anvio7_process

cd $WorkDir

mkdir -p GABA-associated_genes

cd GABA-associated_genes

#prior to extraction, get key files ready
#gene_calls_aa.emapper.annotations: this file has functional annotations for all genes identified
#All-samples-GENE-COVERAGES.txt: this file includes all genes identified in all contigs
#list_gene_bin_info.txt: this file was generated by bash_extract_gene_bin_information.sh, this contains the genes found in each MAG bin, not all contigs will be binned.

#extract key genes from gad operon from functional annotation profile

awk '$6 == "gadB"' $WorkDir/gene_calls_aa.emapper.annotations > gene_calls_aa.emapper.annotations_gadB	
awk '$6 == "gadA"' $WorkDir/gene_calls_aa.emapper.annotations > gene_calls_aa.emapper.annotations_gadA	#this is for e. coli gadA
awk '$6 == "gadC"' $WorkDir/gene_calls_aa.emapper.annotations > gene_calls_aa.emapper.annotations_gadC
awk '$6 == "glsA"' $WorkDir/gene_calls_aa.emapper.annotations > gene_calls_aa.emapper.annotations_glsA

#awk '$6 == "ydcW"' $WorkDir/gene_calls_aa.emapper.annotations | wc -l : 1
#awk '$6 == "ygjG"' $WorkDir/gene_calls_aa.emapper.annotations | wc -l : 0

#awk '$6 == "puuA"' $WorkDir/gene_calls_aa.emapper.annotations | wc -l : 2
#awk '$6 == "puuB"' $WorkDir/gene_calls_aa.emapper.annotations | wc -l : 14
#awk '$6 == "puuC"' $WorkDir/gene_calls_aa.emapper.annotations | wc -l : 3
awk '$6 == "puuD"' $WorkDir/gene_calls_aa.emapper.annotations > gene_calls_aa.emapper.annotations_puuD

awk '$6 == "gabT"' $WorkDir/gene_calls_aa.emapper.annotations > gene_calls_aa.emapper.annotations_gabT

#awk '$6 == "abfH"' $WorkDir/gene_calls_aa.emapper.annotations | wc -l : 0
#awk '$6 == "abfT"' $WorkDir/gene_calls_aa.emapper.annotations | wc -l : 0
awk '$6 == "abfD"' $WorkDir/gene_calls_aa.emapper.annotations > gene_calls_aa.emapper.annotations_abfD

cat gene_calls_aa.emapper.annotations_* | cut -f 1,6 > list_gene_IDs_GABA-associated.txt

#extract gene coverage data

cat list_gene_IDs_GABA-associated.txt | cut -f 1 > temp.txt

cat $WorkDir/All-samples-GENE-COVERAGES.txt | sed -n 1p > temp0
grep -wFf temp.txt $WorkDir/All-samples-GENE-COVERAGES.txt > temp1	#could extract genes that are not in "temp.txt" since this is not the matching based on the first column in coverage data
cat temp0 temp1 > All-samples-GENE-COVERAGES_GABA-associated-genes.txt

grep -wFf temp.txt $WorkDir/gene_calls_DIAMOND-MEGAN_taxonomy.txt > gene_calls_DIAMOND-MEGAN_taxonomy_GABA-associated-genes.txt

rm temp*
